# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 workers
nodes:
# the control plane node config
- role: control-plane
  # kubernetes version 1.26.6 from kind v0.20.0
  image: kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb
# the worker
- role: worker
  # kubernetes version 1.26.6 from kind v0.20.0
  image: kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb
